name: 'Publish Nexus'
description: 'Publish Artifact Nexus'

inputs:
  app-version:
    description: versão da aplicação
    required: true
  file_path:
    description: diretório do arquivo
    required: true
  groupId:
    description: diretório de publish nexus
    required: true
  artifactId: 
    description: Nome da aplicação
    required: true
  repositoryId:
    description: Repositório Nexus
    required: true
    default: Nexus


runs:
  using: composite
  steps:

    - name: Upload
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/publish.sh
        ${{ github.action_path }}/publish.sh
      env:
        file: ${{ inputs.file_path }}
        groupId: ${{ inputs.groupId }}
        artifactId: ${{ inputs.artifactId }}
        packaging: jar 
        version: ${{ inputs.app-version }}
        repositoryId: Nexus 
        username: ${{ vars.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}
        url: ${{ vars.NEXUS_URL }} 
